# Generated by Django 3.2 on 2021-04-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi_num', models.CharField(max_length=10)),
                ('randomID', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='taxis',
            name='avail',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=3),
        ),
    ]
