# Generated by Django 3.2 on 2021-04-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_finishride'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finishride',
            old_name='rate',
            new_name='distance',
        ),
    ]
